### PR TITLE
Imperfect amounts

### PR DESCRIPTION
**Pull request by halogenandtoast**
Handle imprecise amounts like "a few"

### CODE REVIEW

**Comment by balvig** [comment]
@halogenandtoast this looks great!! Handling it inside Ingreedy really simplifies things! 🎈 

Just 2 things:
- Seem to be a typo in https://github.com/cookpad/ingreedy/pull/2/files#diff-264d8e39f4e911fccd13c03abdb2a5baR4 (wondering why the specs would pass. I just added to Travis so we can see on GitHub too)
- I just pulled https://github.com/cookpad/ingreedy/pull/3 into master, so maybe better to target `master` with this one too?

**Comment by halogenandtoast** [comment]
Nice catch on the typo, I failed at rebasing against the `or` branch correctly

**Comment by halogenandtoast** [comment]
@balvig fixed and based on master ♻️

**Comment by balvig** [comment]
Awesome! 👍  

(CI failed on jruby, I guess we don't really care about that though, can remove from travis.yml?)

Usually what we then do is add a spec in the main project to test it works in the context of the app, thanks a lot! 🎉

**Comment by halogenandtoast** [comment]
@balvig what do you mean by main project, are you referring to global-web?

**Comment by sogamoso** [comment]
This looks great!

**Comment by halogenandtoast** [comment]
@balvig updated for case insensitivity ♻️

**Comment by halogenandtoast** [comment]
I'm going to assume since my other PR had a thumbs up that this is good to merge.

**Comment by tapster** [comment]
nice!

**Pull request merged**
